language: ruby
rvm:
  - ruby-2.2
  - ruby-2.3
  - ruby-2.4
  - ruby-2.5
  - ruby-2.6.0-preview2
  - ruby-head

install:
  - bundle install --path vendor/bundle

script:
  - 'bundle exec rspec'
  - 'bundle exec rubocop'

matrix:
  allow_failures:
    - rvm: ruby-2.6.0-preview2
    - rvm: ruby-head
